### ISSUE TITLE
There your #$%^ zip file

### ISSUE THREAD

**Issue by GrenadeSmasher** [MichaelRunzler/ARKCore#3]
[R34Log-Sword_Art_Online-1485077558686.zip](https://github.com/MichaelRunzler/ARKCore/files/721844/R34Log-Sword_Art_Online-1485077558686.zip)

**Comment by MichaelRunzler** [comment]
Crash resulted from an incorrectly computed ICC ColorSpace profile embedded within a JPEG image. Commit ID bb1fd7c added a catch block to alert the user if this happens and give them the URL of the image that caused it.  Also added support for logging exceptions prior to program exit. Latest JAR with fixes included now available.
